INSERT INTO AGENDA (COMPROMISSO, DATA, HORARIO, LOCAL) VALUES ('REUNIAO 1', 0000, 10, 'ESCRITORIO')
INSERT INTO AGENDA (COMPROMISSO, DATA, HORARIO, LOCAL) VALUES ('REUNIAO 2', 0000, 10, 'ESCRITORIO')
INSERT INTO AGENDA (COMPROMISSO, DATA, HORARIO, LOCAL) VALUES ('REUNIAO 3', 0000, 10, 'ESCRITORIO')